app:
  name: droids
  image: registry.midomain.com/droids
  tag: 84b513eb
  port: 8080
  imagePullSecret: gitlab

ha:
  replicas: 3

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100M
    memory: 200Mi

serviceType: NodePort
ingress: 
  enabled: true
  domain: "test.droids.com"
  path: "/"



params:
  models_file: models-test.yaml


hosts:
  gitlab:
    host: droids.test.nodomain
    port: 80
